codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: nearest
  range: "50...100"

  status:
    project:
      default:
        target: auto
        threshold: 20%

    patch: off

    changes: off

comment:
  layout: "header, diff, changes, files, sunburst, uncovered, tree"
  behavior: default
